### ISSUE TITLE
Encuestas y Comunicados

### ISSUE THREAD

**Issue by joadr** [joadr/federeichon#4]
Estamos atrasados, Diego, haz Encuestas y Comunicados, voy a hacer usuarios y votaciones ahora y los subiré para que veas como son. Éstos se guardan en la carpeta de www/imports/api/users/users.jsx y www/imports/api/votings/votings.jsx respectivamente. En tu caso debes cambiar esa ruta a la debida.

cualquier duda, mira el historial de commits

**Comment by joadr** [comment]
Documentación acerca de los SimpleSchema:
https://github.com/aldeed/meteor-simple-schema

**Comment by divegat** [comment]
Ya lo hice y lo sincronicé para que lo veas. Revísalo y cuéntame si es que falta algo

**Comment by joadr** [comment]
Fijate en las comas de este archivo!! https://github.com/joadr/federeichon/blob/master/www/imports/api/news/news.jsx

Te faltaron en el último objeto y te sobró una al final del objeto. Por eso es útil el standard. También es bueno para evitar esto que cuando hagas cambios hayas iniciado el meteor a ver si te tira algún error

**Comment by divegat** [comment]
Ahora si! Lo arreglé, o eso creo jajaja
Si no me equivoco, al Surveys también le sobraba una coma al final
